### ISSUE TITLE
underscore is required for 2.0.11

### ISSUE THREAD

**Issue by sakai135** [Microsoft/tslint-microsoft-contrib#267]
The new rule `react-a11y-anchors` requires the module `underscore`. 

Since `underscore` is only defined as a `devDependency` in `package.json`, it doesn't get installed with `npm install`. That causes errors when trying to run tslint.

```
vscode-tslint: 'Cannot find module 'underscore'' while validating: [file].ts stacktrace: Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> ([path]\node_modules\tslint-microsoft-contrib\reactA11yAnchorsRule.js:9:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by HamletDRC** [comment]
oh no. this must have been installed somehow on our two test systems. 

I will fix it ASAP. 

In the meantime, just turn the rule off.

**Comment by HamletDRC** [comment]
If you turn this rule off then do any of the other rules run?

**Comment by HamletDRC** [comment]
The fix is pushed to the releases branch as well, so you can set your dependency to

    "tslint-microsoft-contrib": "git@github.com:Microsoft/tslint-microsoft-contrib.git@releases"

**Comment by sakai135** [comment]
Turning the rule off doesn't work, as the error hits when loading up the rules, not executing them.

Thanks for the fast fix 👍

**Comment by HamletDRC** [comment]
As a temporary workaround you could also try adding underscore as a devDependency in your own project. Sorry about this.

**Comment by jsynowiec** [comment]
The 2.0.12 release is still not available on npm. When it'll be published?

**Comment by HamletDRC** [comment]
@jsynowiec the npm package is there now. Our npm admin is in California so sometimes we have to wait a few hours :)
